"""Run the review-lane head-to-head register and write REGISTER_RESULTS.md (+ register_results.json).

Usage: python scripts/run_register.py [seeds_per_planted_trader=30] [workers=8]
The reference detectors are INDEPENDENT RE-IMPLEMENTATIONS of published definitions, not rival code.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from engine import register  # noqa: E402
from engine.suite import wilson  # noqa: E402

WALLETS = ROOT.parent / "data" / "trader_samples"       # C:\Users\neon_\bitget\data\trader_samples from loop/
if not WALLETS.is_dir():                                # running from a worktree under loop/.claude/worktrees/<name>
    WALLETS = Path(r"C:\Users\neon_\bitget\data\trader_samples")

SHORT = {
    "TradeMirror LEAK_WEEKEND_RTOKEN": "TM weekend rToken",
    "TradeMirror LEAK_REVENGE_TILT": "TM revenge tilt",
    "TradeMirror LEAK_DISPOSITION_ASYMMETRY": "TM disposition",
    "TradeMirror LEAK_EXHAUSTION_CLUSTER": "TM exhaustion",
    "tradememory size after 2 losses (descriptive)": "tradememory 2-loss size",
    "baseline: always 'size-after-loss'": "baseline",
    "Loop size_after_loss detector": "Loop size habit",
    "Loop hold_asymmetry detector": "Loop hold asymmetry",
    "Loop court: cap 1.5x after a loss": "Loop court cap",
    "Loop halt after 2 losses": "Loop court halt",
}


def cell(k, n, na):
    s = f"{k}/{n}" if n else "-"
    return s + (f" (n.a. {na})" if na else "")


def main() -> None:
    seeds = int(sys.argv[1]) if len(sys.argv) > 1 else 30
    workers = int(sys.argv[2]) if len(sys.argv) > 2 else 8
    res = register.run_register(seeds=seeds, wallet_dir=WALLETS, workers=workers)
    dets = list(SHORT)
    traders, truths = [], {}
    tab = defaultdict(lambda: [0, 0, 0])      # (detector, trader) -> flagged, applicable, not applicable
    priced = defaultdict(list)
    for s, name, truth, ds in res["planted"]:
        if name not in truths:
            traders.append(name)
            truths[name] = truth
        for d in ds:
            c = tab[(d.detector, name)]
            if d.flagged is None:
                c[2] += 1
            else:
                c[1] += 1
                c[0] += bool(d.flagged)
            if d.priced is not None and d.flagged:
                priced[(d.detector, name)].append(d.priced)

    L = ["# Review-lane head-to-head register (scaffolding), measured results", "",
         "**Provenance.** The TradeMirror and tradememory columns are INDEPENDENT RE-IMPLEMENTATIONS OF THEIR PUBLISHED "
         "DEFINITIONS written in `engine/register.py`; no rival code was copied, downloaded or run, so a disagreement below "
         "may be our reading of their definition rather than their product. TradeMirror: README table 'The 4 heuristic rules' "
         "(github.com/hackid02/trademirror). tradememory: README example output (github.com/mnemox-ai/tradememory-protocol), "
         "which is descriptive and issues no verdict; the 'flag' used here is OUR reading convention (>= 5 trades after two "
         "losses and >= 25% of them at 1.5x usual size, anchored on its own example '5 of 20'). Every interpretation choice is "
         "written in the docstring next to each function. Loop columns run our engine unchanged.", "",
         f"Generated by `scripts/run_register.py`: {res['seeds']} seeds per planted trader (seeds {res['seed_range'][0]}-"
         f"{res['seed_range'][1]}), {res['n_perm']} permutations, runtime {res['runtime_s']:.0f}s. Planted traders are SIM_PLANTED; "
         "wallets are REAL_PLATFORM_PUBLIC (someone else's public Hyperliquid fills, never REAL_OWN).", "",
         "## 1. Planted traders: how often each detector flags (flagged / applicable runs)", "",
         "n.a. = the detector returned 'not applicable' or 'underpowered' for that run (Loop says UNDERPOWERED instead of guessing).", "",
         "| detector | " + " | ".join(traders) + " |", "|---|" + "---|" * len(traders),
         "| *what was planted* | " + " | ".join(truths[t] for t in traders) + " |"]
    for d in dets:
        L.append(f"| {SHORT[d]} | " + " | ".join(cell(*tab[(d, t)]) for t in traders) + " |")

    ctrl = traders[0]
    L += ["", f"## 2. False positives on the control ('{ctrl}': no habit, no leak), with 95% Wilson intervals", "",
          "| detector | provenance | flagged on control | rate [Wilson 95%] | mean $ it priced when it flagged |", "|---|---|---|---|---|"]
    fam = {}
    for _, _, _, ds in res["planted"][:len(traders)]:
        for d in ds:
            fam[d.detector] = d.provenance
    for d in dets:
        k, n, na = tab[(d, ctrl)]
        lo, hi = wilson(k, n) if n else (float("nan"), float("nan"))
        pr = priced.get((d, ctrl))
        L.append(f"| {SHORT[d]} | {fam.get(d, '')} | {cell(k, n, na)} | "
                 + (f"{k/n:.1%} [{lo:.1%}, {hi:.1%}]" if n else "n.a.") + " | " + (f"${sum(pr)/len(pr):,.0f}" if pr else "-") + " |")

    L += ["", "Costly-claim false positives on the two costless plants (a detector that PRICES a leak, or a court that ACCEPTS a "
          "rule, is claiming money was lost):", ""]
    for t in traders:
        if "costless" in truths[t]:
            for d in dets:
                k, n, na = tab[(d, t)]
                if n and k and (priced.get((d, t)) or d.startswith("Loop court")):
                    pr = priced.get((d, t))
                    L.append(f"- {t}: {SHORT[d]} flagged {k}/{n}" + (f", pricing a mean ${sum(pr)/len(pr):,.0f} leak that is not in the fills" if pr else ""))

    # agreement on the size-after-loss question
    q = [d for d in dets if d in ("TradeMirror LEAK_REVENGE_TILT", "tradememory size after 2 losses (descriptive)",
                                  "baseline: always 'size-after-loss'", "Loop size_after_loss detector",
                                  "Loop court: cap 1.5x after a loss", "Loop halt after 2 losses")]

    def agreement(rows):
        out = {}
        for a in q:
            for b in q:
                same = tot = 0
                for ds in rows:
                    m = {d.detector: d.flagged for d in ds}
                    if m.get(a) is None or m.get(b) is None:
                        continue
                    tot += 1
                    same += m[a] == m[b]
                out[(a, b)] = (same, tot)
        return out

    def agree_table(title, rows):
        ag = agreement(rows)
        T = ["", title, "", "| | " + " | ".join(SHORT[b] for b in q) + " |", "|---|" + "---|" * len(q)]
        for a in q:
            T.append(f"| {SHORT[a]} | " + " | ".join(
                (f"{ag[(a, b)][0] / ag[(a, b)][1]:.0%} ({ag[(a, b)][1]})" if ag[(a, b)][1] else "-") for b in q) + " |")
        return T

    L += agree_table("## 3. Agreement on the size-after-loss question, all planted runs (percent of runs where both gave "
                     "a yes/no answer and the answers matched; count of such runs in brackets)", [ds for _, _, _, ds in res["planted"]])

    L += ["", "## 4. Sampled public wallets (REAL_PLATFORM_PUBLIC, data/trader_samples)", ""]
    if not res["wallet_dir_present"]:
        L.append("Skipped: the folder is absent on this machine.")
    else:
        L += ["Y = flagged, . = not flagged, n.a. = not applicable / underpowered. TM $ = dollars TradeMirror's published pricing "
              "assigns across its four rules (assumed rates where its table assumes them). Loop cap $ = held-out effect of the cap "
              "rule (positive = the cap would have saved money).", "",
              "| wallet | fills | round trips | " + " | ".join(SHORT[d] for d in dets) + " | TM $ | Loop cap $ (held-out) |",
              "|---|---|---|" + "---|" * len(dets) + "---|---|"]
        for path, nf, nt, ds in res["wallets"]:
            m = {d.detector: d for d in ds}
            fl = " | ".join("n.a." if m[d].flagged is None else ("Y" if m[d].flagged else ".") for d in dets)
            tm = sum((m[d].priced or 0.0) for d in dets if d.startswith("TradeMirror") and m[d].flagged)
            cap = m["Loop court: cap 1.5x after a loss"]
            L.append(f"| {Path(path).stem} | {nf} | {nt} | {fl} | ${tm:,.0f} | "
                     + (f"${cap.priced:,.0f}" if cap.priced is not None else "-") + " |")
        L += agree_table("Agreement on the size-after-loss question across the wallets:", [ds for _, _, _, ds in res["wallets"]])
        L += ["", "No ground truth exists for the wallets, so these columns show who flags what, not who is right."]

    L += ["", "## 5. Where we lose, plainly", "",
          "- Loop has no detector for TradeMirror's weekend-rToken question or its exhaustion-cluster question: those columns "
          "are TradeMirror-only coverage. (Our overtrading detector lives in engine/detectors2.py and is not in this register yet.)",
          "- Loop answers UNDERPOWERED far more often than the heuristics answer anything: on small or low-loss histories we say less.",
          "- TradeMirror's weekend rule prices an ASSUMED 0.5% of notional; on the planted weekend trader the fills contain no extra cost, "
          "so any dollars it prices there are not in the data. That is a property of the published definition, measured here on our plant.",
          "- The comparison is only as faithful as our reading of two README tables; see engine/register.py docstrings for every choice."]
    (ROOT / "REGISTER_RESULTS.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    js = {"planted": [(s, n, t, [d.__dict__ for d in ds]) for s, n, t, ds in res["planted"]],
          "wallets": [(p, nf, nt, [d.__dict__ for d in ds]) for p, nf, nt, ds in res["wallets"]],
          **{k: v for k, v in res.items() if k not in ("planted", "wallets")}}
    (ROOT / "register_results.json").write_text(json.dumps(js, indent=1, default=str), encoding="utf-8")
    print(f"wrote REGISTER_RESULTS.md in {res['runtime_s']:.0f}s")


if __name__ == "__main__":
    main()
